version: "3.8"

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - THE_ODDS_API_KEY=${THE_ODDS_API_KEY}
    expose:
      - 8080
    depends_on:
      - redis

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  redis:
    image: redis/redis-stack-server
    container_name: redis
    restart: always
    ports:
      - "6379"